---
- name: install apache2
  apt: name=apache2 update_cache=yes state=latest

- name: enable modules for socket.io
  apache2_module: name={{item}} state=present
  # ref: https://socket.io/docs/v3/reverse-proxy/#Apache-HTTPD
  with_items:
    - mpm_event
    - authn_file
    - authn_core
    - authz_host
    - authz_groupfile
    - authz_user
    - authz_core
    - headers
    - lbmethod_byrequests
    - proxy
    - proxy_balancer
    - proxy_http
    - proxy_wstunnel
    - rewrite
    - slotmem_shm
    - unixd
  notify:
    - restart httpd
      

