---
- name: Install PostgreSQL
  apt: name={{ item }} update_cache=true state=installed
  with_items:
    - postgresql

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes
