---
- name: Install PostgreSQL
  apt: name={{ item }} update_cache=true state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes
