---
- name: Install temperature
  hosts: temperature
  become: yes
  roles:
    - httpd_w_socketio
    - node14
    - postgres

  tasks:
    - name: create temperature group
      group:
        name: temperature
        state: present

    - name: create temperature user
      user:
        name: temperature
        groups: temperature
        shell: /sbin/nologin
        append: yes
        state: present
        create_home: no

    - name: Copy systemd service file to server
      copy:
        src: temperature.service
        dest: /etc/systemd/system
        owner: root
        group: root
      notify:
        - Start temperature
    
    - name: Copy temperature.conf to apache2
      copy:
        src: temperature.conf
        dest: /etc/apache2/sites-available
        owner: root
        group: root
      notify:
        - Restart apache2

    - name: Enable new site
      shell: /usr/sbin/a2ensite temperature.conf
      notify: Restart apache2

  handlers:
    - name: Start temperature
      systemd:
        name: temperature
        state: started
        enabled: yes
    - name: Restart apache2
      service: name=apache2 state=restarted

